#!/bin/bash
RELEASE_FILE='install-release.sh'
DIR='src'

echo "#!/usr/bin/env bash" > "$RELEASE_FILE"
find $DIR/*.sh |
while read -r file_name;
do
    if [ "${file_name%.*}" = "$DIR/main" ];then continue;fi
    echo "=> Build successful -- ${file_name%.*}"
    cat "$file_name" >> "$RELEASE_FILE"
    echo "" >> "$RELEASE_FILE"
done
cat $DIR/main.sh >> "$RELEASE_FILE"

sed 's/#!\/bin\/bash//g' -i "$RELEASE_FILE"

sed '/^$/d' -i "$RELEASE_FILE"

echo "=----------Build complete!----------="