#!/bin/bash
RELEASE_FILE='release.sh'
DIR='src'

echo "#!/usr/bin/env bash" >"$RELEASE_FILE"
find $DIR/*.sh |
    while read -r file_name; do
        if [ "${file_name%.*}" = "$DIR/main" ]; then continue; fi
        echo -e "\e[0;32m=>\e[0m Build \e[0;32msuccessful\e[0m -- \e[1;34m${file_name%.*}\e[0m"
        cat "$file_name" >>"$RELEASE_FILE"
        echo "" >>"$RELEASE_FILE"
    done
cat $DIR/main.sh >>"$RELEASE_FILE"

sed 's/#!\/bin\/bash//g' -i "$RELEASE_FILE"

sed '/^$/d' -i "$RELEASE_FILE"
echo -e "\e[1;32m=> Build complete!\e[0m"